# ---------- STAGE 1: build ----------
FROM maven:3.9-eclipse-temurin-17 AS build
WORKDIR /app

# cache dependency
COPY pom.xml .
RUN mvn -q -DskipTests dependency:go-offline

# copy source và build jar
COPY src ./src
RUN mvn -q -DskipTests package

# ---------- STAGE 2: run ----------
FROM eclipse-temurin:17-jre
WORKDIR /app

# copy jar
COPY --from=build /app/target/*.jar app.jar

# Copy thư mục data (chứa training.txt)
COPY data /app/data

EXPOSE 8080

ENV JAVA_OPTS="-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0" \
    SPRING_PROFILES_ACTIVE=prod

ENTRYPOINT ["sh","-c","java $JAVA_OPTS -jar /app/app.jar --spring.profiles.active=${SPRING_PROFILES_ACTIVE}"]
